### ISSUE TITLE
求更新

### ISSUE THREAD

**Issue by yueyericardo** [mashaz/NeteaseMusic#1]
应该是网易更新了api
```
ValueError: No JSON object could be decoded
```

如果运行
GetTopAllTime(myuid)也会报错
```
UserWarning: Selenium support for PhantomJS has been deprecated, please use headless versions of Chrome or Firefox instead
  warnings.warn('Selenium support for PhantomJS has been deprecated, please use headless '
Traceback (most recent call last):
  File "compare.py", line 645, in <module>
    GetTopAllTime(10115387)
  File "compare.py", line 105, in GetTopAllTime
    browser = webdriver.PhantomJS(executable_path='/Users/Mashaz/phantomjs-2.1.1-macosx/bin/phantomjs')
  File "/Users/richard/Program/anaconda3/envs/python2/lib/python2.7/site-packages/selenium/webdriver/phantomjs/webdriver.py", line 56, in __init__
    self.service.start()
  File "/Users/richard/Program/anaconda3/envs/python2/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'phantomjs' executable needs to be in PATH. 
```

**Comment by mashaz** [comment]
此项目不再更新抱歉，你有兴趣的话可以fork过去改一下

**Comment by yueyericardo** [comment]
写了个js
http://bs.yyrcd.com/music/?uid=10115387&type=1

type=1 week
Type=0 total
